stages:
  - deploy

deploy:
  stage: deploy
  image: registry.xuelangyun.com/shuzhi-amd64/alpine:3.20
  tags:
    - nexus-tag

  only:
    refs:
      - master
    variables:
      - $NEXUSOPS_MANUAL_DEPLOY == "1"

  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk add --no-cache openssh-client rsync curl jq git ca-certificates
    - eval $(ssh-agent -s)
    - echo "$SERVER_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
    - sh ci/nexusops_deploy.sh
  
  environment:
    name: development
