services:
  hello-world:
    image: registry.xuelangyun.com/shuzhi-amd64/alpine:3.20
    container_name: hello-world
    command: ["sh", "-c", "echo hello-world && sleep infinity"]

networks:
  default:
    name: "${NETWORK}"
    external: true